'use client';
import React from 'react';
import { useResolvedTheme } from '@/lib/useResolvedTheme';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { InventoryRequest, InventoryItem, currency, available, requestTotals } from './inventory';
export function useInventoryStyle() {
  const { isDark } = useResolvedTheme();
  return { isDark, surface: isDark ? 'bg-[#171717] border-[#303030] text-white' : 'bg-white border-[#E5E5E5] text-[#202020]', field: isDark ? 'bg-[#101010] border-[#414141] text-white placeholder:text-zinc-500' : 'bg-white border-[#D8D8D8] text-[#202020] placeholder:text-zinc-400', muted: isDark ? 'text-zinc-400' : 'text-zinc-500', primary: 'bg-[#E5D5B8] text-[#171717] hover:bg-[#D4C3A3]', secondary: isDark ? 'bg-zinc-800 text-white hover:bg-zinc-700' : 'bg-zinc-100 text-zinc-900 hover:bg-zinc-200' };
}
export function InventoryImage({ src, alt, className = 'h-14 w-14' }: {src?: string; alt: string; className?: string}) { return src ? <img src={src} alt={alt} className={`${className} rounded-lg object-cover bg-zinc-200`} onError={(event) => { event.currentTarget.style.display = 'none'; }} /> : <div className={`${className} rounded-lg bg-zinc-500/10 flex items-center justify-center text-xs text-zinc-400`}>No image</div>; }
export function StatusBadge({ status }: { status: string }) { const colors: Record<string, string> = { pending: 'bg-amber-500/15 text-amber-600', accepted: 'bg-emerald-500/15 text-emerald-500', active: 'bg-emerald-500/15 text-emerald-500', rejected: 'bg-red-500/15 text-red-500', cancelled: 'bg-zinc-500/15 text-zinc-400', inactive: 'bg-zinc-500/15 text-zinc-400' }; return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-medium capitalize ${colors[status] || colors.inactive}`}>{status}</span>; }
export function RequestDetailsModal({ request, open, onClose, actions, loading }: { request: InventoryRequest | null; open: boolean; onClose: () => void; actions?: React.ReactNode; loading?: boolean }) { const s = useInventoryStyle(); const totals = requestTotals(request?.items || []); return <Dialog open={open} onOpenChange={(v) => !v && onClose()}><DialogContent className={`w-[calc(100vw-24px)] max-w-[680px] max-h-[90vh] overflow-y-auto border ${s.surface}`}><DialogHeader><DialogTitle>Inventory Request Details</DialogTitle></DialogHeader>{loading ? <p>Loading request...</p> : request && <div className="space-y-5 text-sm"><div className="grid grid-cols-2 gap-3"><div><p className={s.muted}>Request ID</p><p className="font-medium break-all">{request.id}</p></div><div><p className={s.muted}>Status</p><StatusBadge status={request.status}/></div><div><p className={s.muted}>Creative Partner</p><p>{request.creator_name || request.creator_id}</p></div><div><p className={s.muted}>Request Type</p><p>{request.request_type === 'shoot' ? 'Assigned Shoot' : 'Personal Use'}</p></div>{request.shoot_id && <div className="col-span-2"><p className={s.muted}>Shoot</p><p>{request.shoot_name || request.shoot_id} {request.shoot_date || ''}</p></div>}<div><p className={s.muted}>Requested</p><p>{new Date(request.created_at).toLocaleDateString()}</p></div></div>{request.notes && <p className="break-words">Notes: {request.notes}</p>}{request.rejection_reason && <p className="text-red-500">Rejection reason: {request.rejection_reason}</p>}<h3 className="font-semibold">Requested Items</h3><div className="space-y-3">{request.items.map((line) => <div key={line.inventory_item_id} className="flex gap-3 items-center border-b border-current/10 pb-3"><InventoryImage src={line.item_image_snapshot} alt={line.item_name_snapshot}/><div className="flex-1 min-w-0"><p className="font-semibold truncate">{line.item_name_snapshot}</p><p className={s.muted}>{currency(line.unit_price_snapshot)} × {line.quantity}</p></div><strong>{currency(line.line_total)}</strong></div>)}</div><div className="grid grid-cols-3 gap-2 text-center border-t border-current/10 pt-4"><div><p className={s.muted}>Items</p><strong>{totals.total_items}</strong></div><div><p className={s.muted}>Quantity</p><strong>{totals.total_quantity}</strong></div><div><p className={s.muted}>Total</p><strong>{currency(totals.total_amount)}</strong></div></div>{actions}</div>}</DialogContent></Dialog>; }
export function InventoryCard({ item, onClick, selected }: { item: InventoryItem; onClick: () => void; selected?: boolean }) { const s = useInventoryStyle(); return <button disabled={available(item) < 1 || item.status !== 'active'} onClick={onClick} className={`text-left border p-3 rounded-xl disabled:opacity-50 disabled:cursor-not-allowed hover:border-[#E5D5B8] transition-colors ${s.surface} ${selected ? 'ring-2 ring-[#E5D5B8]' : ''}`}><InventoryImage src={item.image_url} alt={item.name} className="w-full h-32 sm:h-40"/><p className="font-semibold mt-3 truncate">{item.name}</p><p className={`text-xs truncate ${s.muted}`}>{item.description || 'No description'}</p><div className="flex justify-between gap-2 mt-2 text-sm"><span>{currency(item.unit_price, item.currency)}</span><span className={s.muted}>{available(item)} available</span></div></button>; }
