'use client';
import React, { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import { ArrowLeft, Minus, Plus, Search, Trash2 } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { InventoryItem, InventoryRequest, ShootOption, RequestLine, RequestType, inventoryApi, available, currency, requestTotals } from '@/components/common/inventory/inventory';
import { InventoryCard, InventoryImage, useInventoryStyle } from '@/components/common/inventory/InventoryUI';
export default function InventoryRequestWizard({open,onClose,onSubmitted,editing}:{open:boolean;onClose:()=>void;onSubmitted:()=>void;editing?:InventoryRequest|null}){
 const s=useInventoryStyle(); const [step,setStep]=useState(0);const [type,setType]=useState<RequestType>('personal');const [shootId,setShootId]=useState('');const [shoots,setShoots]=useState<ShootOption[]>([]);const [catalog,setCatalog]=useState<InventoryItem[]>([]);const [search,setSearch]=useState('');const [items,setItems]=useState<RequestLine[]>([]);const [notes,setNotes]=useState('');const [detail,setDetail]=useState<InventoryItem|null>(null);const [qty,setQty]=useState(1);const [loading,setLoading]=useState(false);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(!open)return;setStep(0);setType(editing?.request_type||'personal');setShootId(editing?.shoot_id||'');setItems(editing?.items||[]);setNotes(editing?.notes||'');setSearch('');setDetail(null);},[open,editing]);
 useEffect(()=>{if(!open)return;let active=true;setLoading(true);setError('');Promise.all([inventoryApi.catalog({page:1,limit:100,search}),inventoryApi.shoots()]).then(([response, assigned])=>{if(active){setCatalog((response.data||[]).filter(x=>x.status==='active'));setShoots(assigned||[]);}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to load inventory');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[open,search]);
 const total=useMemo(()=>requestTotals(items),[items]);const primary=`rounded-lg px-4 py-2.5 font-medium disabled:opacity-50 ${s.primary}`;const secondary=`rounded-lg px-4 py-2.5 font-medium disabled:opacity-50 ${s.secondary}`;
 const changeQuantity=(id:string,n:number)=>{const product=catalog.find(x=>x.id===id);const existing=items.find(x=>x.inventory_item_id===id);const max=product?available(product)+(editing?.items.find(x=>x.inventory_item_id===id)?.quantity||0):existing?.quantity||0;if(n<1||!Number.isSafeInteger(n)||n>max)return;setItems(prev=>prev.map(x=>x.inventory_item_id===id?{...x,quantity:n,line_total:x.unit_price_snapshot*n}:x));};
 const addItem=()=>{if(!detail)return;const current=items.find(x=>x.inventory_item_id===detail.id);const already=editing?.items.find(x=>x.inventory_item_id===detail.id)?.quantity||0;const max=available(detail)+already;const next=qty+(current?.quantity||0);if(!Number.isSafeInteger(qty)||qty<1||next>max)return toast.error(`Available quantity is ${max}`);setItems(prev=>current?prev.map(x=>x.inventory_item_id===detail.id?{...x,quantity:next,line_total:x.unit_price_snapshot*next}:x):[...prev,{inventory_item_id:detail.id,item_name_snapshot:detail.name,item_image_snapshot:detail.image_url,unit_price_snapshot:detail.unit_price,quantity:qty,line_total:detail.unit_price*qty}]);setDetail(null);toast.success('Item added to request');};
 const submit=async()=>{if(items.length===0)return toast.error('Choose at least one item');if(type==='shoot'&&!shootId)return toast.error('Choose an assigned shoot');if(type==='shoot'&&!shoots.some(x=>x.id===shootId))return toast.error('Selected shoot is not assigned');setSubmitting(true);try{await inventoryApi.submit({request_type:type,shoot_id:type==='shoot'?shootId:null,notes,items:items.map(({inventory_item_id,quantity})=>({inventory_item_id,quantity}))},editing?.id);toast.success(editing?'Request updated':'Inventory request submitted');onSubmitted();onClose();}catch(e){toast.error(e instanceof Error?e.message:'Request failed. Check availability and try again');}finally{setSubmitting(false);}};
 return <Dialog open={open} onOpenChange={v=>{if(!v&&!submitting)onClose();}}><DialogContent className={`w-[calc(100vw-20px)] max-w-[860px] max-h-[92vh] overflow-y-auto border ${s.surface}`}><DialogHeader><DialogTitle>{editing?'Edit Inventory Request':'Request for Inventory'}</DialogTitle></DialogHeader><div className={`flex flex-wrap gap-2 border-b border-current/10 pb-4 text-xs ${s.muted}`}>{['Request Type','Browse Inventory','Selected Items','Review Request'].map((label,i)=><span key={label} className={`rounded-full px-3 py-1 ${step===i?'bg-[#E5D5B8] text-black':''}`}>{i+1}. {label}</span>)}</div>{loading&&<p className={s.muted}>Loading available inventory and assigned shoots...</p>}{error&&<p role="alert" className="text-red-500 text-sm">{error} <button className="underline" onClick={()=>setSearch(v=>v+' ')}>Retry</button></p>}
 {step===0&&<div className="space-y-4"><p className="font-medium">What is this inventory request for?</p><div className="grid sm:grid-cols-2 gap-3">{([{id:'personal',label:'Personal Use',sub:'For your own use'},{id:'shoot',label:'Assigned Shoot',sub:'For a shoot assigned to you'}] as const).map(o=><button key={o.id} className={`rounded-xl border p-5 text-left ${s.surface} ${type===o.id?'ring-2 ring-[#E5D5B8]':''}`} onClick={()=>setType(o.id)}><h3 className="font-semibold">{o.label}</h3><p className={`text-sm ${s.muted}`}>{o.sub}</p></button>)}</div>{type==='shoot'&&<label className="block text-sm">Choose Assigned Shoot<select value={shootId} onChange={e=>setShootId(e.target.value)} className={`block w-full mt-2 p-3 border rounded-lg ${s.field}`}><option value="">Select your assigned shoot</option>{shoots.map(shoot=><option key={shoot.id} value={shoot.id}>{shoot.name} ({shoot.id}) {shoot.date||''}</option>)}</select></label>}</div>}
 {step===1&&<div className="space-y-4">{detail?<div className="grid sm:grid-cols-2 gap-5"><InventoryImage src={detail.image_url} alt={detail.name} className="w-full h-56"/><div className="space-y-3"><button onClick={()=>setDetail(null)} className={`text-sm ${s.muted}`}>← Back to inventory</button><h3 className="text-lg font-semibold">{detail.name}</h3><p className={`text-sm ${s.muted}`}>{detail.description}</p><p>{currency(detail.unit_price,detail.currency)}</p><p className={s.muted}>{available(detail)} available</p><div className="flex items-center gap-3"><button className={secondary} onClick={()=>setQty(n=>Math.max(1,n-1))}><Minus size={16}/></button><input aria-label="Item quantity" type="number" min={1} max={available(detail)} value={qty} onChange={e=>setQty(Number(e.target.value))} className={`w-20 rounded-lg p-2 border text-center ${s.field}`}/><button className={secondary} onClick={()=>setQty(n=>Math.min(available(detail),n+1))}><Plus size={16}/></button></div><p>Item Total: <b>{currency(detail.unit_price*qty,detail.currency)}</b></p><button disabled={qty<1||qty>available(detail)} className={primary} onClick={addItem}>Add to Request</button></div></div>:<><label className="relative block"><Search size={16} className="absolute top-3 left-3 opacity-50"/><input placeholder="Search inventory" value={search} onChange={e=>setSearch(e.target.value)} className={`border rounded-lg py-2.5 pl-9 pr-3 w-full ${s.field}`}/></label><div className="grid grid-cols-2 md:grid-cols-3 gap-3">{catalog.map(item=><InventoryCard key={item.id} item={item} selected={items.some(x=>x.inventory_item_id===item.id)} onClick={()=>{setDetail(item);setQty(1);}}/>)}</div>{catalog.length===0&&!loading&&<p className={s.muted}>No available inventory items found.</p>}</>}</div>}
 {step===2&&<div className="space-y-3">{items.length===0?<p className={s.muted}>No items selected. Browse inventory to add items.</p>:items.map(line=><div key={line.inventory_item_id} className="flex flex-wrap items-center gap-3 rounded-lg border border-current/10 p-3"><InventoryImage src={line.item_image_snapshot} alt={line.item_name_snapshot}/><div className="flex-1 min-w-28"><p className="font-semibold">{line.item_name_snapshot}</p><p className={s.muted}>{currency(line.unit_price_snapshot)} each</p></div><input aria-label={`Quantity for ${line.item_name_snapshot}`} type="number" min={1} value={line.quantity} className={`w-20 p-2 rounded-lg border ${s.field}`} onChange={e=>changeQuantity(line.inventory_item_id,Number(e.target.value))}/><b>{currency(line.unit_price_snapshot*line.quantity)}</b><button aria-label={`Remove ${line.item_name_snapshot}`} onClick={()=>setItems(prev=>prev.filter(x=>x.inventory_item_id!==line.inventory_item_id))} className="text-red-500"><Trash2 size={18}/></button></div>)}<button className={secondary} onClick={()=>setStep(1)}>+ Add More Items</button></div>}
 {step===3&&<div className="space-y-4 text-sm"><div className={`border rounded-lg p-4 space-y-3 ${s.surface}`}><div className="flex justify-between"><h3 className="font-semibold">Request Information</h3><button className="underline" onClick={()=>setStep(0)}>Edit</button></div><p>Type: {type==='shoot'?'Assigned Shoot':'Personal Use'}</p>{type==='shoot'&&<p>Shoot: {shoots.find(x=>x.id===shootId)?.name||shootId}</p>}<label className="block">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Additional notes (optional)" className={`block mt-1 w-full min-h-20 rounded-lg border p-3 ${s.field}`}/></label></div><div className="flex justify-between"><h3 className="font-semibold">Requested Inventory</h3><button className="underline" onClick={()=>setStep(2)}>Edit Items</button></div>{items.map(line=><div key={line.inventory_item_id} className="flex justify-between gap-3"><span>{line.item_name_snapshot} × {line.quantity}</span><span>{currency(line.quantity*line.unit_price_snapshot)}</span></div>)}</div>}
 <div className="border-t border-current/10 pt-4 mt-3"><div className="flex flex-wrap justify-between gap-3 text-sm mb-4"><span>Different Items: <b>{total.total_items}</b></span><span>Total Quantity: <b>{total.total_quantity}</b></span><span>Total Amount: <b>{currency(total.total_amount)}</b></span></div><div className="flex justify-between gap-2"><button className={secondary} onClick={()=>step?setStep(step-1):onClose()}>{step?<><ArrowLeft size={15} className="inline mr-1"/>Back</>:'Cancel'}</button>{step===3?<button disabled={submitting||loading} onClick={()=>void submit()} className={primary}>{submitting?'Submitting...':editing?'Save Request':'Submit Inventory Request'}</button>:<button disabled={loading||!!error||(step===0&&type==='shoot'&&!shootId)||(step===2&&items.length===0)||step===1&&!!detail} onClick={()=>setStep(step+1)} className={primary}>Continue</button>}</div></div></DialogContent></Dialog>;
}
