"use client";

import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { CircleDollarSign, Clock3, Medal } from "lucide-react";
import type React from "react";
import { currency } from "./types";

const chartData = [{ month: "Jan", value: 34 }, { month: "Feb", value: 38 }, { month: "Mar", value: 40 }, { month: "Apr", value: 57 }, { month: "May", value: 66 }, { month: "Jun", value: 49 }, { month: "Jul", value: 56 }];
const metrics = [{ key: "value", label: "Quote Value", value: "$24.5M", icon: CircleDollarSign }, { key: "sent", label: "Quotes Sent", value: "128", icon: Clock3 }, { key: "won", label: "Deals Won", value: "32", icon: Medal }, { key: "revenue", label: "Won Revenue", value: "$8.7M", icon: CircleDollarSign }];
const Title = ({ children }: { children: React.ReactNode }) => <div className="mb-3 flex items-center gap-2 text-[10px] text-white/80"><span className="h-4 w-px bg-[#ead7b0]" />{children}</div>;

export function QuoteAnalyticsOverview({ selectedMetric, onMetricClick, compact = false }: { selectedMetric?: string; onMetricClick?: (metric: string) => void; compact?: boolean }) { return <div className="grid gap-3 xl:grid-cols-[1.65fr_.95fr]"><section className="rounded-xl border border-[#2c2c2c] bg-[#171717] p-3 xl:h-[377px]"><Title>Quote Performance</Title><div className="h-[196px] rounded-xl bg-[#101010] p-3"><div className="grid h-full grid-cols-2 gap-3">{metrics.map(({ key, label, value, icon: Icon }) => <button key={key} onClick={() => onMetricClick?.(key)} className={`rounded-md p-2 text-left ${selectedMetric === key ? "bg-[#ead7b0] text-[#111]" : "hover:bg-white/5"}`}><div className="flex justify-between text-[9px] opacity-80">{label}<span className="grid h-5 w-5 place-items-center rounded-full bg-[#2e2d2b] text-[#e8d1ab]"><Icon size={11} /></span></div><p className="mt-1 text-lg font-semibold leading-none">{value}</p><p className="mt-1 text-[8px] text-emerald-400">+3% <span className="opacity-60">from last month</span></p></button>)}</div></div><div className="mt-3 h-[142px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ left: -20, right: 8, top: 12 }}><defs><linearGradient id="quoteAnalyticsGradient" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#E8D1AB" stopOpacity={.2} /><stop offset="1" stopColor="#E8D1AB" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "#777", fontSize: 9 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#777", fontSize: 9 }} width={26} /><Tooltip contentStyle={{ background: "#151515", border: "1px solid #3d3d3d", borderRadius: 8, fontSize: 11 }} /><Area type="monotone" dataKey="value" stroke="#E8D1AB" strokeWidth={1.2} fill="url(#quoteAnalyticsGradient)" activeDot={{ r: 4, fill: "#151515", stroke: "#E8D1AB" }} /></AreaChart></ResponsiveContainer></div></section><Conversion />{!compact && <OpenPipeline />}</div>; }

function Metric({ value, label, tone }: { value: string; label: string; tone: string }) { return <div className="rounded-lg bg-[#101010] p-2"><b className={`text-sm ${tone}`}>{value}</b><p className="mt-1 text-[8px] text-white/50">• {label}</p></div>; }
function Conversion() { return <section className="rounded-xl border border-[#2c2c2c] bg-[#171717] p-3 xl:h-[377px]"><Title>Conversion Performance</Title><div className="relative mx-auto grid h-[196px] max-w-[290px] place-items-center overflow-hidden"><div className="absolute h-44 w-44 rounded-full bg-[repeating-radial-gradient(circle_at_center,transparent_0,transparent_9px,#272727_10px,#272727_11px)]" /><svg className="relative h-44 w-44 -rotate-[110deg]" viewBox="0 0 120 120"><circle cx="60" cy="60" r="45" fill="none" stroke="#42d0df" strokeWidth="9" strokeLinecap="round" strokeDasharray="72 211" /><circle cx="60" cy="60" r="32" fill="none" stroke="#a897eb" strokeWidth="9" strokeLinecap="round" strokeDasharray="55 146" /><circle cx="60" cy="60" r="19" fill="none" stroke="#f2e781" strokeWidth="9" strokeLinecap="round" strokeDasharray="34 85" /></svg><div className="absolute rounded-lg bg-white px-3 py-1 text-xs font-bold text-black">25% <span className="text-[8px] font-normal">Deal won</span></div></div><div className="grid grid-cols-2 gap-2"><Metric value="25%" label="WIN RATE" tone="text-[#f2e781]" /><Metric value="$27,188" label="AVG. DEAL VALUE" tone="text-[#b6a1ef]" /></div><div className="mt-2"><Metric value="35.5%" label="QUOTE-TO-CASH CONVERSION" tone="text-[#42d0df]" /></div></section>; }
function OpenPipeline() { return <section className="xl:col-span-2 rounded-xl border border-[#2c2c2c] bg-[#171717] p-3"><div className="flex items-start justify-between"><div><Title>Open Pipeline</Title><p className="text-2xl font-semibold text-[#ead7b0]">$12.4M</p><p className="mt-1 text-[9px] text-white/45">Total Active Pipeline Value</p></div><div className="rounded-xl border border-white/15 bg-[#101010] px-5 py-2 text-center"><b className="text-xl">46</b><p className="text-[10px]">Active Quotes</p></div></div><div className="mt-3 grid grid-cols-3 gap-4 rounded-lg bg-[#101010] p-3">{[["Sent", "20 Quotes", "from-[#1b1923] to-[#8676e8]"], ["Accepted", "14 Quotes", "from-[#173322] to-[#39c762]"], ["Partially Paid", "12 Quotes", "from-[#242216] to-[#dacb43]"]].map(([label, count, gradient]) => <button key={label} className="border-l-2 border-white pl-2 text-left"><p className="text-xs text-white/65">{label}</p><p className="text-[9px] text-[#b5a4ff]">{count}</p><div className={`mt-2 h-8 rounded bg-gradient-to-r ${gradient}`} /></button>)}</div></section>; }
export function QuotePipeline() { return <section className="rounded-xl border border-[#2c2c2c] bg-[#171717] p-3"><div className="grid gap-3 md:grid-cols-[95px_1fr]"><div className="flex flex-col border-r border-white/5"><Title>Quotes Overdue</Title><b className="text-xl text-[#ead7b0]">14</b><p className="mt-1 text-[9px] text-white/45">Need Follow-Up</p><button className="mt-auto grid h-5 w-5 place-items-center rounded-full bg-[#444] text-[9px]">↗</button></div><div className="rounded-lg bg-[#101010] p-3"><p className="text-[10px] text-white/60">Pipeline At Risk</p><div className="mt-3 grid grid-cols-3 text-[8px]"><span className="text-[#41c7e3]">• SENT - 6 QUOTES</span><span className="text-[#42d96a]">• ACCEPTED - 5 QUOTES</span><span className="text-[#e7d045]">• PARTIALLY PAID - 3 QUOTES</span></div><div className="mt-2 flex h-11 overflow-hidden rounded"><div className="grid flex-[1.6] place-items-center bg-gradient-to-b from-[#50d4fa] to-[#167baf] text-xs font-bold text-black">$1.6M</div><div className="grid flex-[1.3] place-items-center bg-gradient-to-b from-[#c2efad] to-[#6bcf70] text-xs font-bold text-black">$1.3M</div><div className="grid flex-1 place-items-center bg-gradient-to-b from-[#fff4ba] to-[#d5bd5a] text-xs font-bold text-black">$0.9M</div></div><p className="mt-3 flex items-center gap-2 text-center text-xs text-[#ead7b0] before:h-px before:flex-1 before:bg-white/20 after:h-px after:flex-1 after:bg-white/20">Total {currency(3800000)}</p></div></div></section>; }
