-- =====================================================
-- Revure Crew Members Import Script (Auto-generated)
-- =====================================================
-- Generated on: 2026-01-13T22:55:00.409Z
-- Total crew members: 46

-- =====================================================
-- STEP 1: Clean existing crew members (optional)
-- =====================================================
-- WARNING: This will delete all existing crew members
-- Uncomment the line below to execute
-- DELETE FROM crew_members;

-- =====================================================
-- STEP 2: Insert new crew members
-- =====================================================

INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Jiovani', 'Medina', 'jiovani@nomattermedia.com', '8017421384', '["videography","photography"]', 'Salt Lake City', 'Utah', 133, '["4K Video Camera","On-camera lighting","On-camera microphone","Gimbal","Flash"]', NULL, 'https://drive.google.com/file/d/1zyoXNgEZktjo9s-4-uiUo4pyflwIW9EL/view?usp=drive_link', 'videography, photography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Victor', 'Chavana', 'victorchavana@yahoo.com', NULL, '["videography"]', 'Remote', 'US', 100, '[]', NULL, 'https://drive.google.com/file/d/1IxlwsIUIqDPlDn-FOVMvYhRRavSi-LEW/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('John', 'Heyward', 'skyislandphoto@gmail.com', '4436299011', '["videography","photography"]', 'DMV', 'Maryland', 100, '["Canon 1D","Canon 7d","Canon 5d MKII","Canon Rebel T2i","Canon 1ds mark 2","Canon Powershot Pro 1","Nikon D700","Nikon D2x","Panasonic DVX100b Video Camera"]', 'https://skyislandphotography.com/?page_id=141', 'https://drive.google.com/file/d/17GI-hzBvQ-1tUw2hTBFqErkjztmL9Aio/view?usp=drive_link', 'videography, photography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Mikey', 'Donaldson Jr.', 'creative.team@bloomingseedmedia.com', '2407231400', '["videography","photography"]', 'Nashville', 'Tennessee', 100, '[]', NULL, 'https://drive.google.com/file/d/1LcEgKsCyPxHAoYjaucEgXIYF4KjEhfs9/view?usp=drive_link', 'videography, photography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Wayne', 'Johnson', 'wdoug95608@aol.com', '9162171509', '["videography","photography","drone"]', 'San Jose', 'California', 97, '["Sony A7III Camera","Various Lenses","Sony A7IVr Camera","Speedlite Flash","Sony HD Video cameras","Mavic Drone","Tripods","Ronin RC2 Stabiliser","Wireless Lapel mics","DJI Mic3","H4n Recorder","Shotgun mics"]', 'https://waynedouglasproductions.com/', 'https://drive.google.com/file/d/11Bx-L2iea9TMDFrJuZDXES8DQfQAmEMy/view?usp=drive_link', 'videography, photography, drone specialist with professional experience');

INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Vincent', 'Garza', 'swolenerdproductions@gmail.com', '8173698235', '["videography"]', 'Fort Worth', 'Texas', 180, '["8 cameras"]', 'https://www.youtube.com/watch?v=2zgn2es6tSU', 'https://drive.google.com/file/d/11fFECJ-PpcKdQh7c4Q1CISQtYalHjHGA/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Robert', 'Bragg', 'robert.bragg6@revure.placeholder', '8059063062', '["videography","drone"]', 'Paso Robles', 'California', 75, '["BLACKMAGIC 6K CINEMA CAMERA","PANASONIC 4K CAMERA WITH SERVO LENSES","Multiple Prime and Zoom Lenses","DJI PHANTON 4 PRO 4K DRONE","Professional Lighting Setup","Wireless Audio Systems","Full Production Package"]', 'BRAGGMEDIAWORKS.COM', 'https://drive.google.com/file/d/12zGDpP1Odbqk42hhHls1iuaSnTH4BSGN/view?usp=drive_link', 'videography, drone specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Joshua', 'Amos Cupp', 'josh@cuppsphotography.com', '7084464453', '["photography"]', 'Remote', 'Illinois', 100, '["Professional 4K Cameras","Audio","Lighting"]', 'https://www.instagram.com/cupps_photography/', 'https://drive.google.com/file/d/15XVOF0sBCpEBg3DPE9oFArWh025L16gp/view?usp=drive_link', 'photography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Jacob', 'Perkins', 'jacob.perkins@hensbreadproductions.com', '5128932709', '["videography"]', 'Austin', 'Texas', 22, '[]', NULL, 'https://drive.google.com/file/d/16CgOO9W_5cDMKNsLNRT72TqJ2GyIE-Fc/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Corey', 'Bishop', 'hipsob@gmail.com', '8185229273', '["videography"]', 'Los Angeles', 'California', 90, '["Sony PXW-FS7''s","prime lenses","Sony A7s2","Lights","Drone","Gimbals","Lavs","Tripod","Sliders","Sound","Other related Production gear"]', 'http://www.bishopentgroup.com/', 'https://drive.google.com/file/d/170XBc1h4SobFhcL3kmdbhd6uHBa0t51r/view?usp=drive_link', 'videography specialist with professional experience');

INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Tylah', 'Blaize', 'tyblaize1@gmail.com', '2546691966', '["videography"]', 'Little River Academy', 'Texas', 75, '["4K Video Camera","Lighting","Audio","Stabilizer"]', NULL, 'https://drive.google.com/file/d/1aFbDJ5kfZyCxTr_wPijlBZ-CcJEWAy47/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Jordan', 'Berns', 'jordanbernsbusiness@gmail.com', '4088244063', '["videography"]', 'Seattle', 'Washington', 100, '["Canon c300 mkII","Canon C100 mkii","DZOFilm lenses","Sigma 18-35mm lens","Professional audio setup with Sennheiser wireless systems","LED lighting panels","Gimbal stabilization"]', 'www.jsbvideo.com', 'https://drive.google.com/file/d/1Ag1oFFKHxoZ6ezFqv5_RUBSmT-NG4xD2/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Nikhil', 'Kolachalama', 'nkolachalama@gmail.com', '6095782683', '["videography"]', 'Lakewood', 'New Jersey', 83, '["4K Video Camera","Cinema Lighting","Audio (Wireless Lavaliers)","28-75mm zoom"]', NULL, 'https://drive.google.com/file/d/1c7LUeHqN1R7BbFZuJjOlhcsQsjjHKCRl/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Daniel', 'Calderon', 'decvisuals.96@gmail.com', '9292617661', '["videography"]', 'Dallas', 'Texas', 131, '["4K Video","Lighting","Audio","Zoom Recorder","Boom Mic"]', NULL, 'https://drive.google.com/file/d/1cISt6F5Pbr-GWXO4Lb_tQ66iccaLzV5e/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Yasmine', 'Img', 'yasminemphoto@gmail.com', '3109088923', '["videography","photography"]', 'Los Angeles', 'California', 100, '["canon 5D mark 4","canon 5D mark 2","50mm lens","24-70mm lens","3 flashes","1 ofc light","1 white umbrella","1 tripod"]', 'https://www.yasminemerciar.com/', 'https://drive.google.com/file/d/1EabxGURWQP22GlYRi7pHzjwXBorJi2x9/view?usp=drive_link', 'videography, photography specialist with professional experience');

INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Alyssa', 'Williams', 'amcw.creative@gmail.com', '8136951879', '["videography"]', 'Miami', 'Florida', 100, '[]', 'rolls.bublup.com/yamsville/', 'https://drive.google.com/file/d/1H1dUvRHcEm80m7GlTe8qQJz8RaGheQ_Z/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Marcelo', 'Echeverria', 'puravidamediaco@gmail.com', '2137916274', '["videography"]', 'Los Angeles', 'California', 200, '["4K Video Camera","Lighting","Audio","Stabilizer"]', NULL, 'https://drive.google.com/file/d/1HkZ9QrcYgEQOlgHsh8adBe1GkxtQBhes/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Kyaw', 'Aye', 'shalamorningstudio@gmail.com', '9193701230', '["videography"]', 'Durham', 'North Carolina', 64, '["4K Video Camera","Lighting","Audio (lavalier or shotgun mic)","Stabilizer"]', NULL, 'https://drive.google.com/file/d/1hlVYiIWymsPHtqMx0dM4nxo7wPAkNkKG/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Hannah', 'McWhorter', 'hello@hannahwhomedia.com', '3134346149', '["videography"]', 'Warren', 'Michigan', 100, '[]', NULL, 'https://drive.google.com/file/d/1hxHh-xTtXAAXDQDdQa4Cki5AhZuIoD-Q/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Gary', 'Ahmed', 'garyahmedfilm@gmail.com', '2039108599', '["videography"]', 'Los Angeles', 'California', 125, '["BMPCC 4K","BMPCC 6K PRO","Canon 5D m4","Multiple Cinema Lenses","Professional Lighting Package","Gimbals","Audio Equipment","Full Production Suite"]', 'www.garyahmed.com', 'https://drive.google.com/file/d/1I4BuMMxBdnyhfrIen3slNGX_GQz5MeOk/view?usp=drive_link', 'videography specialist with professional experience');

INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Kenze', 'Lee Rogers', 'kandkproductions2011@gmail.com', NULL, '["videography"]', 'Remote', 'US', 210, '[]', NULL, 'https://drive.google.com/file/d/1J7fhk4zsFcy8h-XJdUWDdbzPR9129Bw2/?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Joshua', 'Gerber', 'reigncinematography@gmail.com', '3166312470', '["videography","drone"]', 'Wichita', 'Kansas', 100, '["Canon R5C","Canon R6 x2","Multiple lenses (24-70mm","24-105mm","70-200mm)","DJI RS2 Pro Gimbal","DJI Air 2S drone","Professional audio with F3 Zoom recorder","Aputure lighting package"]', NULL, 'https://drive.google.com/file/d/1jIBb7OZaqtIsVSrWEP77ijbBrMwFb5H-/view?usp=drive_link', 'videography, drone specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Eddie', 'Hurskin', 'theblackumbrellastudio@gmail.com', '2562899673', '["videography"]', 'Montgomery', 'Alabama', 125, '[]', NULL, 'https://drive.google.com/file/d/1JJedbQ1qf8M-t6llgNA1IdEIjFIiSUI5/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('AutumnK', 'Whisnant', 'akwmediallc@gmail.com', '3212661749', '["videography"]', 'Kansas City', 'Missouri', 75, '["Canon R6 Mark II","EOS R"]', 'www.akwmedia.net', 'https://drive.google.com/file/d/1jRqVr-l52X0wKmYikO25_yGj8qSs4TyG/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Mazahir', 'Bhagat', 'mazahirbhagat97@gmail.com', '3467193727', '["videography"]', 'Inez', 'Texas', 150, '[]', NULL, 'https://drive.google.com/file/d/1KNC-mX7ECGj9B3ayDyY4MV0Ds5Zykdvd/view?usp=drive_link', 'videography specialist with professional experience');

INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Joshua', 'Reid', 'joshua.reid25@revure.placeholder', '5634249811', '["videography"]', 'Las Vegas', 'Nevada', 100, '["Sony Fx3","Sony a7iii","Small rig cage","DJI RS3 Pro gimbal","wireless rode mics","portable light cubes"]', 'https://joshfilmedit.my.com/', 'https://drive.google.com/file/d/1latX9TMgpEfIXBCT-Yn8ldhV5xfdF22w/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Christopher', 'Ramirez', 'crazycoolstudio@gmail.com', '2104212916', '["videography"]', 'San Antonio', 'Texas', 100, '["4K Video Camera","Cinematic Lighting","Audio (Wireless Lavalier)","Stabilizer"]', NULL, 'https://drive.google.com/file/d/1LhaTZIxhtjK5az45Wn6N3D8Grjaa9S5O/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Stefano', 'Morales Franke', 'smorles90@yahoo.com', '7866204279', '["videography"]', 'Deltona, Fort Lauderdale', 'Florida', 67, '["Professional 4K Camera","Audio","Cinematic Lighting","Stabilizer","2 wireless lav mic","Zoom audio recorder"]', NULL, 'https://drive.google.com/file/d/1LnMMMxVFgq7ICyqJXrKEMCLAHTroO7dX/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Elliott', 'McCracken', 'info@flashy-photography.com', '6617429345', '["audio"]', 'Remote', 'US', 131, '["Sony ZV-E10","DJI Osmo Pocket 3","DJI Avata 2 (FPV)","DJI Mic Mini (2x mics + lavs)","Portable Battery Bank"]', 'https://www.instagram.com/flashyPhotography661/', 'https://drive.google.com/file/d/1m_ZtzRM0esr6SUAUifUDkwd1pgujH_rs/view?usp=drive_link', 'audio specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Jesse', 'Sieden', 'jessesieden@gmail.com', '2062456191', '["videography"]', 'Seattle', 'Washington', 50, '["4K Video Camera","Lighting","Audio","Stabilizer"]', NULL, 'https://drive.google.com/file/d/1m1HhXvlQPHE2ye9wKbfHO2IoRjn8XGh3/view?usp=drive_link', 'videography specialist with professional experience');

INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Nigel', 'Gayle', 'lightsoutdevelopment@outlook.com', '8139449828', '["videography"]', 'Tampa', 'Florida', 100, '[]', NULL, 'https://drive.google.com/file/d/1OLo4CHvEx8KxXbUUaTbp1ZXbZtB1nNVR/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Innokentii', 'Plavko', 'kotupsfilm@gmail.com', '2797867739', '["videography","photography"]', 'Chico', 'California', 125, '[]', 'https://kotupsfilm.com', 'https://drive.google.com/file/d/1oQlrMc6IItDii34lhOGdFLxNZTHjyVYJ/view?usp=drive_link', 'videography, photography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Tan', 'Loc Huynh', 'huynhimages@gmail.com', '9292548081', '["videography","photography"]', 'Philadelphia', 'Pennsylvania', 67.5, '["Canon r6","Sony fx3","flash","continuous light"]', 'www.448studio.com', 'https://drive.google.com/file/d/1OQZWkSozXK0jXq23hSS-wlwAulZpPQ3B/view?usp=drive_link', 'videography, photography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Jeremiah', 'Silva', 'jeremiahhuchel@gmail.com', '6466232155', '["videography","photography"]', 'Newark, Edgewater', 'New Jersey', 80, '["4K Video Cameras","Lighting","Audio","Tripods"]', 'https://bighutchstudio.com/', 'https://drive.google.com/file/d/1PnYQXcB-G4b7HO-wL9_5au5eMl-CQNgj/view?usp=drive_link', 'videography, photography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Tyler', 'McGhee', 'tyler@piqtu.com', '4802214737', '["videography"]', 'Albuquerque, Phoenix, Chandler', 'Arizona', 140, '["Canon C200","Canon C100 Mk II","Canon 6D Mk II","DJI Mavic Air2s","Professional Cinema Lenses","Gimbal","Lighting","Professional Audio"]', 'www.piqtu.com', 'https://drive.google.com/file/d/1qCXQhKhAQU2s4ZrfZ43VzFzpoLlW7EGO/view?usp=drive_link', 'videography specialist with professional experience');

INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Allie', 'Nelson', 'alliehgp@gmail.com', '9515220321', '["videography","photography"]', 'Austin', 'Texas', 75, '[]', 'https://www.hicksgirlProductions.com/', 'https://drive.google.com/file/d/1QM6mLD916zbR8N-E3nLV8vHOOgpbe85V/view?usp=sharing', 'videography, photography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Taylor', 'Bradberry', 'taylorbradberryfilms@gmail.com', '9712634805', '["videography"]', 'Portland', 'Oregon', 84, '[]', NULL, 'https://drive.google.com/file/d/1qS4H6EReyOyl_dBSbyX-8n1vxv09Auq_/view?usp=sharing', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Ryan', 'Cabana', 'rcabana21@yahoo.com', '8609182453', '["videography"]', 'Boston', 'Massachusetts', 100, '["GH5","GH4","Ronin-S","Godox VL150","Tascam DR-40","Tascam DR-10L","DJI Phantom 3"]', 'ryancabana.com', 'https://drive.google.com/file/d/1RaNYArEmn2Vs3phbxgOGbCoiMUNLErgM/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('McKenzie', 'Murieen', 'mckenzieleephoto@gmail.com', '5305981906', '["videography"]', 'Remote', 'Nevada', 100, '["Canon mirrorless"]', 'https://www.instagram.com/mckenzie.leephotography', 'https://drive.google.com/file/d/1rN4Q39CIQue2MJuFuIydWqxOFBV5MRzB/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Kyle', 'Sawyer', 'kandkproductions2011@gmail.com', '5179938358', '["videography","photography"]', 'Shelbyville', 'Michigan', 67, '["Sony A7IV","Sony A7III","Sony A7RII","Sony A7RIV","Multiple Sony lenses (16-35mm","24mm","35mm","24-70mm","85mm","70-200mm)","DJI Mavic Air 2S","Zhiyun Weebill S Gimbal","Professional audio"]', 'https://kandkproductionsco.pixieset.com/sawyerfilms/', 'https://drive.google.com/file/d/1RwcByy_XpZhPCEiOE1Tr573yELPEaljJ/view?usp=drive_link', 'videography, photography specialist with professional experience');

INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Weston', 'Flemmons', 'wesflemmons@gmail.com', '9017864494', '["videography"]', 'New York City', 'New York', 65, '["Fuji Film XH1 Camera","Fujinon XF Zoom 16-55mm F/2.8","GVM 3-Point Light Kit","Professional Audio","DJI Ronin-SC Pro","DJI Mavic Mini 3 Pro"]', 'https://wesflemmons.com', 'https://drive.google.com/file/d/1scZZJocUdWKvAo5xPGLQLxd2z4Tf9By6/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Timothy', 'Neal', 'tim_neal@me.com', '9188577783', '["videography","photography"]', 'Seattle', 'Washington', 75, '["EOS R5","Canon R5","Wide Angle Lens","Zoom Lens","Godox flash","H4N recorder","Tascam lavalier","Tripods","Monopods"]', 'http://instagram.com/timnealPhoto/', 'https://drive.google.com/file/d/1VFIz0wpUX_kOc_Stt84gN2sthtXzu6zM/view?usp=drive_link', 'videography, photography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Joseph', 'Anderson', 'josephedwardanderson@gmail.com', '5034815582', '["videography"]', 'Portland', 'Oregon', 40, '["Panasonic GH5","various lenses","gimbal","basic lighting gear","lavalier mic"]', 'https://vimeo.com/user79957480', 'https://drive.google.com/file/d/1VKkPtC3zpvC9VYDYq6idbbTGjzDA-tvj/view?usp=drive_link', 'videography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Colby', 'Robins', 'chasingrobinsmedia@gmail.com', '8016499170', '["videography","photography"]', 'Salt Lake City', 'Utah', 70, '["Canon R6 Mark II","on camera LED panel","2 Bluetooth mics","RODE shotgun mic"]', 'www.chasingrobinsmedia.com', 'https://drive.google.com/file/d/1wik4pkO_YS7s2D-QtAFS__bcXqEAS-UT/view?usp=drive_link', 'videography, photography specialist with professional experience');
INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Vedant', 'Chavan', 'dopvedant@gmail.com', '8189342350', '["videography"]', 'San Francisco', 'California', 100, '[]', NULL, 'https://drive.google.com/file/d/1XRBPQQ9ZlsOWrpc4Ns-jo6Tu8RvXe2e4/view?usp=drive_link', 'videography specialist with professional experience');

INSERT INTO crew_members (first_name, last_name, email, phone_number, skills, city, state, hourly_rate, equipment_ownership, portfolio_url, profile_image, bio)
VALUES ('Marlon', 'Medina & Crew', 'marlon@goldenmedinallc.com', NULL, '["videography"]', 'St. George', 'Utah', 600, '[]', NULL, 'https://drive.google.com/file/d/1yzxK4tDAZzGAkjmEpgpXgCpkgdUKUNWP/view?usp=drive_link', 'videography specialist with professional experience');

-- =====================================================
-- STEP 3: Verify import
-- =====================================================
-- SELECT COUNT(*) as total_crew_members FROM crew_members;
-- SELECT first_name, last_name, email, city, state, hourly_rate FROM crew_members ORDER BY created_at DESC LIMIT 20;
